name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install colorama aiocontextvars win32-setctime pre-commit tox pytest pytest-cov pytest-mypy-plugins freezegun exceptiongroup mypy Sphinx sphinx-rtd-theme myst-parser build twine

      - name: Run tests
        run: tox -e tests